# Dependencies
gems: [jekyll-paginate]
markdown: kramdown

# Custom entries
title: Electrosheep
description: The blog of Michael DeGraw
author: Michael DeGraw
github: https://github.com/electr0sheep
username: electr0sheep
about: I am a student currently attending Texas Tech University. I no longer wish to persue a career in artificial intelligence. Cybersecurity is what interests me now. The only problem is, I'm not smart enough to be good at it! :(
urls:
    - text: Categories
      url: /category/random
    - text: Introduction
      url: /intro/
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/electr0sheep
url: https://electr0sheep.com
enforce_ssl: electr0sheep.com
baseurl: ""
comments: true

# Pagination
paginate: 20
per_page: 20
paginate_path: "/page:num/"
