# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title.html
# relative_permalinks: true

# Setup
title:               Catskull.net
tagline:             'The blog of David DeGraw'
description:         'Catskull.net: The personal blog of David DeGraw, documenting my finds as a web developer and electrical engineering student.'
url:                 http://catskull.net
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              David DeGraw
  url:               https://twitter.com/davidwdegraw
  email:             bro@catskull.net

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
  - jekyll-sitemap
