# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            electr0sheep.com
#tagline:          'A Jekyll theme'
#description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
#url:              http://lanyon.getpoole.com

author:
  name:           'electrosheep'
#  url:            https://twitter.com/mdo

paginate:         7

# Custom vars
#version:          2.0.0

github:
  repo:           https://github.com/electr0sheep
