# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup

author:
  name:           'electrosheep'

paginate:         2

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
